// ============================================
// Meeting Docs Chatbot
// ============================================
// Lazy-mounted pop-out chatbot that generates branded HTML documents
// (Meeting Recaps, MAPs, Biweekly Updates, Pre-Meeting Agendas) from
// partner call transcripts via Claude API.

import { el, uuid } from '../utils/dom.js';
import { CONFIG, getRuntimeConfig } from '../config.js';
import { appendRow, updateRow, isConfigured, addDemoRow, updateDemoRow } from '../sheets.js';
import { stripHtml } from './quill-editor.js';
import { formatDate, nowISO } from '../utils/date.js';
import { showToast } from './toast.js';

// ============================================
// System Prompt
// ============================================

const MEETING_DOCS_SYSTEM_PROMPT = `You are the Recast Meeting Docs assistant for partner success managers. You help create polished, branded HTML documents from call transcripts for partner-facing use.

# Your role

You receive the full set of call transcripts for one partner as context in the first user message. When the user asks you to generate a document, you read the relevant transcripts, then produce a clean, accurate, client-safe HTML document.

# Document types you support

1. **Meeting Recap** — summary of one call: attendees, key topics, decisions, action items, next steps.
2. **Mutual Action Plan (MAP)** — forward-looking joint plan between Recast and the partner, using the PCP (Problem → Capability → Path-forward) model. Includes milestones, owners, dates, status.
3. **Recap + MAP** — a Meeting Recap immediately followed by a MAP section. This is the most common default when the user asks for "a document" without specifying.
4. **Biweekly Update** — status digest covering the last 2 weeks: wins, blockers, in-flight items, upcoming.
5. **Pre-Meeting Agenda** — forward-looking agenda for an upcoming call: context, topics, questions, desired outcomes.

If the user's request is ambiguous about which document type, ask one short clarifying question before generating. If they specify a date range like "last 30 days" or "last two meetings," select the matching transcripts from your context.

# Accuracy rules (critical)

- Only use facts, names, dates, numbers, and quotes that appear in the provided transcripts.
- Never invent details. If a transcript doesn't mention something the user asks about, say so and ask if they want to proceed with what's available.
- When writing action items or milestones, attribute owners by name only if they were named in the transcript. Otherwise use "Recast" or "Partner" as the owner.
- Preserve specific dollar figures, dates, and product names exactly as stated.

# Client-safe filtering

These types of content must NEVER appear in the generated document:
- Internal pricing negotiations, discount discussions, margin calculations
- Critical comments about competitors (OK to mention competitors factually)
- Private opinions about individuals ("Dave seemed distracted today")
- Anything marked as confidential or off-the-record
- Speculative revenue forecasts not confirmed by the partner

If the transcripts contain such content, quietly exclude it — don't call attention to the exclusion.

# Output format

When generating or updating a document, structure your response as:

1. A brief one-sentence lead-in (plain text) describing what you generated.
2. Then the full document wrapped in a :::HTML code block like this:

:::HTML
<div style="font-family: Inter, system-ui, sans-serif; max-width: 720px; margin: 0 auto; padding: 24px; color: #1a1a2e;">
  <h1 style="color: #0000CC; font-size: 24px; margin: 0 0 8px 0;">Document Title</h1>
  <!-- ... rest of document ... -->
</div>
:::

3. A short closing line offering follow-ups (e.g., "Let me know if you want to adjust the milestones or add more context.")

# HTML styling requirements

- Use inline styles only — no <style> blocks, no external CSS, no <link> tags.
- No <script> tags, no external images, no iframes.
- Recast brand colors: primary #0000CC (deep blue), accent #00BFFF (cyan), text #1a1a2e, muted #6B7280.
- Use a single root <div> with Inter/system-ui font and max-width: 720px.
- Hierarchy: <h1> for title (#0000CC), <h2> for section headers (border-bottom: 2px solid #00BFFF), <h3> for subsections.
- For MAPs, use a <table> with columns: Milestone / Owner / Target Date / Status. Give the header row background #0000CC with white text. Alternate row backgrounds for readability.
- Status cells: use colored pills (spans) — green #0F7A3F for Complete, cyan #00BFFF for In Progress, gray #6B7280 for Not Started, red #CC2222 for At Risk.
- For bullet lists, use colored disc markers (wrap bullets in spans with color).
- Include a small footer: "Generated by Recast Partner Portal · {today's date}".

# Updating existing documents

When asked to update a document, always emit the FULL replacement HTML block, not a diff. Preserve sections the user didn't ask to change.

# Conversation style

Be concise and collaborative. Don't over-explain. Acknowledge the request briefly, then deliver. If you need clarification, ask one question — don't pepper the user with multiple.`;

// ============================================
// Module State
// ============================================

const state = {
  mounted: false,
  containerEl: null,
  windowEl: null,
  chatEl: null,
  textareaEl: null,
  sendBtnEl: null,
  headerTitleEl: null,
  headerSubtitleEl: null,

  conversationHistory: [], // [{ role, content }]
  currentPartner: null,
  currentTranscripts: [],
  currentMode: 'create', // 'create' | 'update'
  currentDoc: null, // { _rowIndex, document_id, ... } in update mode
  onSavedCb: null,

  abortController: null,
  isBusy: false,
  isOpen: false,
  sessionId: 0, // Bumped on open/close so in-flight responses from a prior session can be discarded
};

// ============================================
// Public API
// ============================================

/**
 * Open the Meeting Docs chatbot.
 * @param {Object} opts
 * @param {Object} opts.partner - Partner object (partner_id, display_name, ...)
 * @param {Array} opts.transcripts - Full list of transcript objects for this partner
 * @param {'create'|'update'} opts.mode
 * @param {Object} [opts.existingDoc] - Required when mode === 'update'
 * @param {Function} [opts.onSaved] - Called after a successful save
 */
export function openMeetingDocs({ partner, transcripts = [], mode = 'create', existingDoc = null, onSaved = null }) {
  ensureMounted();

  // Check API key up front for a clean UX
  const apiKey = getRuntimeConfig('ANTHROPIC_API_KEY');
  if (!apiKey) {
    showToast('Anthropic API key not set. Configure it on the Setup page first.', 'error');
    return;
  }

  // Invalidate any in-flight request from a previous session (e.g. the user
  // opened the chatbot for another partner without closing it first).
  state.sessionId++;
  if (state.abortController) {
    try { state.abortController.abort(); } catch { /* ignore */ }
    state.abortController = null;
  }
  state.isBusy = false;
  if (state.sendBtnEl) {
    state.sendBtnEl.disabled = false;
    state.sendBtnEl.textContent = 'Send';
  }

  state.currentPartner = partner;
  state.currentTranscripts = transcripts;
  state.currentMode = mode;
  state.currentDoc = existingDoc;
  state.onSavedCb = onSaved;

  // Update header
  state.headerTitleEl.textContent = `Meeting Docs — ${partner.display_name || 'Partner'}`;
  state.headerSubtitleEl.textContent = mode === 'update'
    ? `Updating: ${existingDoc?.title || 'document'}`
    : `${transcripts.length} transcript${transcripts.length === 1 ? '' : 's'} in context`;

  // Reset chat UI and conversation
  state.chatEl.innerHTML = '';
  state.conversationHistory = [];

  // Reset textarea state so stale text / expanded height from a previous
  // session doesn't carry over.
  state.textareaEl.value = '';
  state.textareaEl.style.height = 'auto';

  // Seed context: first message is a hidden user turn with all transcripts
  const contextMessage = buildTranscriptContextMessage(partner, transcripts);
  state.conversationHistory.push({ role: 'user', content: contextMessage });

  if (mode === 'create') {
    // Seed assistant greeting (stored in history and rendered)
    const greeting = `Hi — I have ${transcripts.length} transcript${transcripts.length === 1 ? '' : 's'} for ${partner.display_name} loaded. I can generate a Meeting Recap, Mutual Action Plan, Recap + MAP, Biweekly Update, or Pre-Meeting Agenda. What would you like?\n\nTry things like: "Create a Recap + MAP from the most recent call" or "Build a biweekly update from the last 2 weeks".`;
    state.conversationHistory.push({ role: 'assistant', content: greeting });
    renderAssistantBubble(greeting);
  } else if (mode === 'update' && existingDoc) {
    // Combine "here is current doc" + greeting into a single assistant turn
    // so the history alternates user/assistant correctly for the API.
    const combinedContext = `Here is the current saved document titled "${existingDoc.title}" (${existingDoc.doc_type}). I'll preserve this as the baseline and apply whatever changes you request.\n\n:::HTML\n${existingDoc.html_content}\n:::\n\nWhat would you like to change?`;
    state.conversationHistory.push({ role: 'assistant', content: combinedContext });
    // Render a friendlier version in the UI (hide the raw HTML from the user)
    const uiGreeting = `I've loaded "${existingDoc.title}". What changes would you like to make? You can describe updates in plain language — e.g., "Mark milestone 2 as complete" or "Add a section about the POC timeline".`;
    renderAssistantBubble(uiGreeting);
  }

  openPopup();
  setTimeout(() => state.textareaEl?.focus(), 50);
}

// ============================================
// DOM Mount (lazy)
// ============================================

function ensureMounted() {
  if (state.mounted) return;

  const closeBtn = el('button', {
    class: 'meeting-docs__close',
    title: 'Close',
    html: '<svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M4.5 4.5l9 9M13.5 4.5l-9 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>',
    onClick: closePopup,
  });

  state.headerTitleEl = el('div', { class: 'meeting-docs__header-title' }, 'Meeting Docs');
  state.headerSubtitleEl = el('div', { class: 'meeting-docs__header-subtitle' }, '');

  const header = el('div', { class: 'meeting-docs__header' },
    el('div', {},
      state.headerTitleEl,
      state.headerSubtitleEl,
    ),
    closeBtn,
  );

  state.chatEl = el('div', { class: 'meeting-docs__chat' });

  state.textareaEl = el('textarea', {
    class: 'meeting-docs__textarea',
    placeholder: 'Describe the document you want…',
    rows: '1',
    onKeydown: (e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        handleSend();
      }
    },
    onInput: (e) => {
      // Auto-grow
      e.target.style.height = 'auto';
      e.target.style.height = Math.min(120, e.target.scrollHeight) + 'px';
    },
  });

  state.sendBtnEl = el('button', {
    class: 'btn btn--primary btn--sm meeting-docs__send',
    onClick: handleSend,
  }, 'Send');

  const inputRow = el('div', { class: 'meeting-docs__input-row' },
    state.textareaEl,
    state.sendBtnEl,
  );

  state.windowEl = el('div', { class: 'meeting-docs__window' },
    header,
    state.chatEl,
    inputRow,
  );

  state.containerEl = el('div', { class: 'meeting-docs meeting-docs--hidden' }, state.windowEl);
  document.body.appendChild(state.containerEl);

  state.mounted = true;
}

function openPopup() {
  state.containerEl.classList.remove('meeting-docs--hidden');
  state.isOpen = true;
}

function closePopup() {
  // Invalidate any in-flight request so its late-arriving response is discarded.
  state.sessionId++;
  if (state.abortController) {
    try { state.abortController.abort(); } catch { /* ignore */ }
    state.abortController = null;
  }
  state.isBusy = false;
  if (state.sendBtnEl) {
    state.sendBtnEl.disabled = false;
    state.sendBtnEl.textContent = 'Send';
  }
  state.containerEl.classList.add('meeting-docs--hidden');
  state.isOpen = false;
}

// ============================================
// Conversation Helpers
// ============================================

function buildTranscriptContextMessage(partner, transcripts) {
  const sorted = [...transcripts].sort((a, b) =>
    new Date(b.conversation_date || b.created_at) - new Date(a.conversation_date || a.created_at)
  );

  let ctx = `# Partner Context\n\nPartner: ${partner.display_name || 'Unknown'}\n`;
  if (partner.partner_type) ctx += `Type: ${partner.partner_type}\n`;
  if (partner.tier) ctx += `Tier: ${partner.tier}\n`;
  if (partner.region) ctx += `Region: ${partner.region}\n`;
  ctx += `\n# Call Transcripts (${sorted.length})\n\n`;

  if (sorted.length === 0) {
    ctx += '_No transcripts have been recorded for this partner yet._\n';
  } else {
    sorted.forEach((t, i) => {
      const date = formatDate(t.conversation_date) || formatDate(t.created_at) || 'Undated';
      const text = stripHtml(t.transcript_text || '').trim();
      ctx += `## Transcript ${i + 1} — ${date}\n\n${text}\n\n---\n\n`;
    });
  }

  ctx += `\n_The above is background context. I'll send my actual request in the next message._`;
  return ctx;
}

async function handleSend() {
  if (state.isBusy) return;
  const text = state.textareaEl.value.trim();
  if (!text) return;

  state.textareaEl.value = '';
  state.textareaEl.style.height = 'auto';

  // Render user bubble
  renderUserBubble(text);

  // Append to history
  state.conversationHistory.push({ role: 'user', content: text });

  // Capture the session ID so we can discard a response that arrives after
  // the popup has been closed or reopened for a different partner.
  const mySessionId = state.sessionId;

  // Call API
  state.isBusy = true;
  state.sendBtnEl.disabled = true;
  state.sendBtnEl.textContent = '…';
  const typingEl = renderTypingIndicator();

  try {
    state.abortController = new AbortController();
    const response = await callMeetingDocsAPI(state.conversationHistory, state.abortController.signal);
    if (mySessionId !== state.sessionId) return; // Stale — ignore
    typingEl.remove();

    state.conversationHistory.push({ role: 'assistant', content: response });

    const { prose, htmlBlocks } = parseHtmlBlocks(response);
    if (prose) renderAssistantBubble(prose);
    htmlBlocks.forEach(html => renderDocCard(html));

    scrollChatToBottom();
  } catch (err) {
    if (mySessionId !== state.sessionId) return; // Stale — ignore (popup closed / reopened)
    typingEl.remove();
    if (err.name === 'AbortError') {
      // Silent — user closed popup
    } else {
      renderErrorBubble(err.message || 'Request failed');
    }
  } finally {
    // Only reset busy/controller state if we're still the current session.
    // A stale handleSend must NOT wipe out a newer session's abortController.
    if (mySessionId === state.sessionId) {
      state.abortController = null;
      state.isBusy = false;
      state.sendBtnEl.disabled = false;
      state.sendBtnEl.textContent = 'Send';
    }
  }
}

// ============================================
// Claude API Call
// ============================================

async function callMeetingDocsAPI(messages, signal) {
  const apiKey = getRuntimeConfig('ANTHROPIC_API_KEY');
  if (!apiKey) {
    throw new Error('API key not set. Configure it on the Setup page.');
  }

  // Filter out assistant-only "seed" messages that shouldn't be sent as actual
  // assistant turns (API requires messages to alternate user/assistant).
  // Our conversationHistory is already built to alternate correctly.
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 8192,
      system: MEETING_DOCS_SYSTEM_PROMPT,
      messages: messages.map(m => ({ role: m.role, content: m.content })),
    }),
    signal,
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || `API error: ${response.status}`);
  }

  const data = await response.json();
  return data.content
    .filter(block => block.type === 'text')
    .map(block => block.text)
    .join('\n');
}

// ============================================
// Response Parsing
// ============================================

function parseHtmlBlocks(text) {
  // Tolerate any (or no) whitespace between the fence and the HTML so that
  // responses like "</div>:::" or "</div> :::" still match.
  const htmlBlocks = [];
  const prose = text.replace(/:::HTML\s*([\s\S]*?)\s*:::/g, (_, html) => {
    htmlBlocks.push(html.trim());
    return '';
  }).trim();
  return { prose, htmlBlocks };
}

// ============================================
// Rendering
// ============================================

function renderUserBubble(text) {
  const bubble = el('div', { class: 'meeting-docs__bubble' }, text);
  const msg = el('div', { class: 'meeting-docs__msg meeting-docs__msg--user' }, bubble);
  state.chatEl.appendChild(msg);
  scrollChatToBottom();
  return msg;
}

function renderAssistantBubble(text) {
  const bubble = el('div', { class: 'meeting-docs__bubble' }, text);
  const msg = el('div', { class: 'meeting-docs__msg meeting-docs__msg--assistant' }, bubble);
  state.chatEl.appendChild(msg);
  scrollChatToBottom();
  return msg;
}

function renderErrorBubble(message) {
  const bubble = el('div', { class: 'meeting-docs__error' }, `Error: ${message}`);
  const msg = el('div', { class: 'meeting-docs__msg meeting-docs__msg--assistant' }, bubble);
  state.chatEl.appendChild(msg);
  scrollChatToBottom();
}

function renderTypingIndicator() {
  const typing = el('div', { class: 'meeting-docs__typing' },
    el('span', {}),
    el('span', {}),
    el('span', {}),
  );
  const bubble = el('div', { class: 'meeting-docs__bubble' }, typing);
  const msg = el('div', { class: 'meeting-docs__msg meeting-docs__msg--assistant' }, bubble);
  state.chatEl.appendChild(msg);
  scrollChatToBottom();
  return msg;
}

function renderDocCard(html) {
  const iframe = el('iframe', {
    class: 'meeting-docs-doc-card__iframe',
    sandbox: 'allow-same-origin',
  });
  // srcdoc must be set after creation
  iframe.srcdoc = html;

  const saveBtn = el('button', {
    class: 'btn btn--primary btn--sm',
    onClick: () => handleSaveDoc(html, saveBtn),
  }, state.currentMode === 'update' ? 'Update Document' : 'Save to Partner');

  const copyBtn = el('button', {
    class: 'btn btn--secondary btn--sm',
    onClick: () => {
      navigator.clipboard.writeText(html).then(
        () => showToast('HTML copied to clipboard', 'success'),
        () => showToast('Failed to copy', 'error'),
      );
    },
  }, 'Copy HTML');

  const card = el('div', { class: 'meeting-docs-doc-card' },
    el('div', { class: 'meeting-docs-doc-card__header' }, 'Generated Document Preview'),
    iframe,
    el('div', { class: 'meeting-docs-doc-card__actions' }, saveBtn, copyBtn),
  );

  state.chatEl.appendChild(card);
  scrollChatToBottom();
  return card;
}

function scrollChatToBottom() {
  requestAnimationFrame(() => {
    state.chatEl.scrollTop = state.chatEl.scrollHeight;
  });
}

// ============================================
// Save to Sheet
// ============================================

async function handleSaveDoc(html, btn) {
  if (!state.currentPartner) return;
  btn.disabled = true;
  btn.textContent = 'Saving…';

  try {
    const partner = state.currentPartner;
    const title = extractTitle(html) || `${partner.display_name} Document`;
    const docType = inferDocType(state.conversationHistory, html);

    if (state.currentMode === 'update' && state.currentDoc) {
      const values = [
        state.currentDoc.document_id,
        partner.partner_id,
        partner.display_name,
        title,
        docType || state.currentDoc.doc_type || 'recap',
        html,
        state.currentDoc.status || 'active',
        state.currentDoc.created_at || nowISO(),
        nowISO(),
      ];
      if (isConfigured()) {
        await updateRow(CONFIG.SHEET_PARTNER_DOCUMENTS, state.currentDoc._rowIndex, values);
      } else {
        updateDemoRow(CONFIG.SHEET_PARTNER_DOCUMENTS, state.currentDoc._rowIndex, values);
      }
      // Refresh local reference
      state.currentDoc = { ...state.currentDoc, html_content: html, title, doc_type: values[4], updated_at: values[8] };
      showToast('Document updated', 'success');
    } else {
      const now = nowISO();
      const values = [
        uuid('doc'),
        partner.partner_id,
        partner.display_name,
        title,
        docType || 'recap',
        html,
        'active',
        now,
        now,
      ];
      if (isConfigured()) {
        await appendRow(CONFIG.SHEET_PARTNER_DOCUMENTS, values);
      } else {
        addDemoRow(CONFIG.SHEET_PARTNER_DOCUMENTS, values);
      }
      showToast('Document saved to partner', 'success');
    }

    btn.textContent = 'Saved ✓';
    if (state.onSavedCb) {
      try { state.onSavedCb(); } catch { /* ignore */ }
    }
  } catch (err) {
    showToast(err.message || 'Failed to save', 'error');
    btn.disabled = false;
    btn.textContent = state.currentMode === 'update' ? 'Update Document' : 'Save to Partner';
  }
}

function extractTitle(html) {
  // Try <h1> first, then <h2>, then fall back to first heading-ish line
  const h1Match = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  if (h1Match) return stripHtml(h1Match[1]).trim().slice(0, 120);
  const h2Match = html.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
  if (h2Match) return stripHtml(h2Match[1]).trim().slice(0, 120);
  return '';
}

function inferDocType(history, html) {
  // Scan the user's most recent requests and the generated HTML for keywords
  const recentUserText = history
    .filter(m => m.role === 'user')
    .slice(-3)
    .map(m => m.content.toLowerCase())
    .join(' ');
  const htmlLower = html.toLowerCase();
  const combined = recentUserText + ' ' + htmlLower;

  if (/\bpre[-\s]?meeting\b|\bagenda\b/.test(combined)) return 'pre-meeting';
  if (/\bbiweekly\b|\bbi-weekly\b|\bbi weekly\b/.test(combined)) return 'biweekly';
  if (/\brecap\s*\+\s*map\b|\brecap and map\b/.test(combined)) return 'map';
  if (/\bmutual action plan\b|\bmap\b/.test(combined)) return 'map';
  if (/\brecap\b|\bmeeting recap\b/.test(combined)) return 'recap';
  return 'recap';
}
